// Stable strings persisted in ActivityLog.action. Treat these as an append-
// only enum: renaming a value would make historical log entries unreadable.
module.exports = {
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED: 'AUTH_PASSWORD_RESET_COMPLETED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',

  PROFILE_UPDATED: 'PROFILE_UPDATED',
  AVATAR_UPDATED: 'AVATAR_UPDATED',

  FRIEND_REQUEST_SENT: 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_REJECTED: 'FRIEND_REQUEST_REJECTED',
  FRIEND_REQUEST_CANCELLED: 'FRIEND_REQUEST_CANCELLED',
  FRIEND_REMOVED: 'FRIEND_REMOVED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',

  GROUP_CREATED: 'GROUP_CREATED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  GROUP_DELETED: 'GROUP_DELETED',
  GROUP_MEMBER_ADDED: 'GROUP_MEMBER_ADDED',
  GROUP_MEMBER_REMOVED: 'GROUP_MEMBER_REMOVED',
  GROUP_MEMBER_LEFT: 'GROUP_MEMBER_LEFT',
  GROUP_MEMBER_BANNED: 'GROUP_MEMBER_BANNED',
  GROUP_MEMBER_UNBANNED: 'GROUP_MEMBER_UNBANNED',
  GROUP_ROLE_CHANGED: 'GROUP_ROLE_CHANGED',
  GROUP_OWNERSHIP_TRANSFERRED: 'GROUP_OWNERSHIP_TRANSFERRED',

  MESSAGE_DELETED_BY_MODERATOR: 'MESSAGE_DELETED_BY_MODERATOR',
  CHAT_EXPORTED: 'CHAT_EXPORTED',
};
